### ISSUE TITLE
No hot reload

### ISSUE THREAD

**Issue by mvrhov** [mariusbalcytis/webpack-bundle#19]
I don't know how to describe this properly but I'm having a problem with hot reloading.

When I run the `app/console maba:webpack:dev-server` everything gets "compiled" without any errors.
However If I then go and change one less file and save it the change is not picked up. So Then I have to kill the server and start it again which s troublesome as even on a latest i7 it takes about 30 seconds for that to startup and compile everything.

Any suggestions on how to debug that or what to try.

Now the development environment is as following:
PhpStorm on windows with a network mapped drive. Everything else is running inside a VM on my computer.

Let me just say that the assetic watch has no problem in such environment.

**Comment by mariusbalcytis** [comment]
Changes in asset files are handled by [webpack-dev-server](https://webpack.github.io/docs/webpack-dev-server.html) itself. Symfony command parses twig files, builds config for aliases and entry files and then runs webpack-dev-server internally.

Could you reproduce this with some minimum set-up, so it would be easier to spot the problem?

Is anything written into output of command as the file is changed? Is this only happening to less files or to javascript files, too?

**Comment by mvrhov** [comment]
It happened with all files.
The problem seems to be a feature of Php/WebStorm named "safe write". This first saves changes into temporary file and then overwrites the original one. This did work with assetic, but nodejs or webpack seem not to catch such changes.
