### ISSUE TITLE
Add sass and less by default

### ISSUE THREAD

**Issue by Big-Shark** [mariusbalcytis/webpack-bundle#2]
Hi, what do you think about add sass and less in standard config?

**Comment by mariusbalcytis** [comment]
Yup, I think that's reasonable - babel is loaded by default, less and sass are really commonly used.

**Comment by antoligy** [comment]
Surely these should be on a per-use-case basis?  There's no requirement that users use the stock webpack configuration

**Comment by mariusbalcytis** [comment]
Yes, but I think more often than not developers will use one or another. And it saves time if you can just use it without any additional googling and configuration.
Webpack is nice in that way - we only get some additional files in `node_modules`, but installing additional loaders does affect anything we get in production.

**Comment by antoligy** [comment]
Right, nonetheless this now implies more dependencies than are actually needed to use the bundle 😞
