### ISSUE TITLE
i get error when i delete a file

### ISSUE THREAD

**Issue by leeir** [mariusbalcytis/webpack-bundle#29]
i get error when i delete a file which webpack watching, such as :
![wechatimg42](https://cloud.githubusercontent.com/assets/5330071/20556943/50d16116-b1a4-11e6-8bc0-9ed275278b89.jpeg)

i can`t stop process in terminal , what should i do?

￼￼

**Comment by mariusbalcytis** [comment]
I've made some corrections:
- in case of exception, inner dev-server process is stopped correctly, so this should not happen again
- in case entry file is deleted, exception is passed to exception handler, so in dev environment it will just ignore it (wait for an error to be resolved)

Thanks for the feedback!
