### ISSUE TITLE
Different port for webpack-dev-server

### ISSUE THREAD

**Issue by antoligy** [mariusbalcytis/webpack-bundle#4]
Following along from #3, mostly marking as a placeholder to myself as I'll attempt to PR this:

Right now the documentation about binding webpack to a different port, or host, is unclear.  Perhaps this can even be moved to a different configuration file due to this being a fairly common option to set (that way it can be propagated to the dev bundle automagically?).

**Comment by mariusbalcytis** [comment]
I don't think we need a separate configuration file - how do you imagine to do that? Or did you mean separate configuration option?

Documentation and/or example is definitely needed.

Do you think `0.0.0.0` should be default for host option? As running in VMs and/or containers are really common nowadays.

Only downside as I see would be allowing to connect from outside the localhost - possible downgrade in security while in development environment in some scenarios (no firewall, untrusted users in same LAN, something to hide in your assets).

**Comment by mariusbalcytis** [comment]
Some documentation was added regarding the command line arguments and setting `0.0.0.0` as a host.
