### ISSUE TITLE
Bundle provider directory override

### ISSUE THREAD

**Issue by vicnicius** [mariusbalcytis/webpack-bundle#61]
Hi,

Thanks for the great work done here so far. It will be amazingly useful in a project I'm currently working on. 

I would like to know if there is any way to override https://github.com/mariusbalcytis/webpack-bundle/blob/6dce0c055ef4857a5c67e8fb48604edf86cca44f/src/Resources/config/services/providers.xml#L24 . In my project structure we have the templates next to their controllers, so it would be awesome if I could add them from there also.

Thank you once again!

**Comment by mariusbalcytis** [comment]
You could just register another asset provider using tag like this:

```xml
<service id="my_custom_asset_provider"
                 parent="maba_webpack.asset_provider.twig_directory.base"
                 public="false">
    <tag name="maba_webpack.asset_provider"/>
    <argument type="service">
        <service class="Maba\Bundle\WebpackBundle\AssetProvider\DirectoryProvider\BundlesDirectoryProvider">
            <argument type="service" id="kernel"/>
            <argument>/Controller</argument>
            <argument>%maba_webpack.enabled_bundles%</argument>
        </service>
    </argument>
</service>
```

Replace `/Controller` with directory relative to each bundle.

**Comment by vicnicius** [comment]
Thank you very much for the fast response! Will try it out later today.
