### ISSUE TITLE
Add the option "Access-Control-Allow-Origin" to the devServer config

### ISSUE THREAD

**Issue by leogout** [mariusbalcytis/webpack-bundle#62]
Hi, I had to add `headers: { 'Access-Control-Allow-Origin': '*' },` to the devServer section in `webpack.config.js` in order to get the hot reload to work.
This was the error message:
![capture du 2017-05-16 14-06-42](https://cloud.githubusercontent.com/assets/9843962/26105088/f00f2720-3a40-11e7-8cc2-ff9e25a61321.png)
I found the solution on this issue: https://github.com/gaearon/react-hot-loader/issues/56
My configuration:
* Brand new Symfony 3.2.8
* Running on 127.0.0.1:8000 (`php bin/console server:start`)
* Running `php bin/console maba:webpack:dev-server`

If this solution suits you, i can make a PR.

Thanks for your work, you are saving me a lot of time !

Cheers.

**Comment by m-albo** [comment]
+1 Thx @leogout for this fix!

**Comment by mariusbalcytis** [comment]
Thanks for the fix!

I've also found some related changes needed for newer webpack-dev-server in case it's ran on another host, added needed configuration parameters to readme.
