### ISSUE TITLE
HMR with {% webpack css %}

### ISSUE THREAD

**Issue by vicnicius** [mariusbalcytis/webpack-bundle#63]
Would it be possible to make HMR work with assets inserted into templates with the `{% webpack css 'path/to/less/file.less' %}`? If so, could you point me out how to do it? 

Thank you once again!

**Comment by mariusbalcytis** [comment]
Well, I did not test it just know, but as far as I know, it should work just fine.

Are you using `app/console maba:webpack:dev-server`? As HMR only works with dev-server.

Are you changing something inside `file.less` and it does not reload in browser, or do you change some other things?

**Comment by vicnicius** [comment]
I'm changing file.less. Everything works almost fine. The bundle is updated and the page even reloads, but this is not actually hot module reloading. But I took a bit deeper look and it looks like something you have to setup within webpack. Not all loaders have the module replacement feature enabled. For now I'm staying with it as it is but later I'll see if it is possible to come up with any type of workaround. If I do that, I'll make sure I share the solution here. 

Once again, thank you.

**Comment by mariusbalcytis** [comment]
Basically, to get HMR working, extract-text-webpack-plugin is not needed in development.

You would get a flash of styles, though, as styles are loaded by JavaScript. 

Also, you cannot use css/less files directly as an entry point, if not using that plugin. 

You cpuld just configure `extract_css: false` in your webpack parameters in config_dev.yml.

Of course, not the nicest solution... But in any case, for HMR to work, some JavaScript is still needed. And if you use css directly as an entry point, in theory you include none script tags at all. So this could get quite complicated to set-up correctly.

**Comment by vicnicius** [comment]
It was what I thought. But the way it is, with live-reloading is still good enough. Thank you.
