### ISSUE TITLE
HMR not starting with HTTPS

### ISSUE THREAD

**Issue by m-albo** [mariusbalcytis/webpack-bundle#64]
Hi, 

SSL is needed for my project so i would like enable https with Webpack. But when i do that, HMR doesn't start (empty console).

My configuration

    maba_webpack:
        config:
            parameters:
                dev_server_public_path: https://my_project/compiled/
        bin:
            dev_server:
                arguments:
                    - --hot
                    - --inline
                    - --https
                    - --host
                    - 0.0.0.0

Any idea?

**Comment by m-albo** [comment]
For those interested, I finally fix my problem by using this configuration :

    devServer: {
            https: true,
            headers: { 'Access-Control-Allow-Origin': '*' },
            overlay: {
                warnings: false,
                errors: true
            }
        }

and by replacing 

    publicPath = DEV_SERVER ? 'http://localhost:8080/compiled/' : '/compiled/';

with

    publicPath = DEV_SERVER ? '//localhost:8080/compiled/' : '/compiled/';

**Comment by mariusbalcytis** [comment]
CORS headers were fixed with #62.

Additionally:
- links were changed to start with `//` as you've suggested;
- added configuration option in default `webpack.config.js` to pass `https: true` from `config.yml` if needed.

Thanks!
