### ISSUE TITLE
Support for PHP 7.3.2

### ISSUE THREAD

**Issue by matthew-gill** [mariusbalcytis/webpack-bundle#94]
Hey, I'm upgrading our envs to use PHP 7.3.2 but webpack-bundle has the following limit:

`requires php ^5.3.2 || >=7.0 <7.2 -> your PHP version (7.3.2)`

Is it possible to add support for 7.3.2?

**Comment by aalwash** [comment]
@mariusbalcytis any update on this?
We could make PR, if you approve it?

**Comment by mariusbalcytis** [comment]
Released in 1.1.3.

**Comment by aalwash** [comment]
Thanks! This also helps us upgrade to 7.4 now ;)
